name: GitHub Actions Demo
on:
  push:
    branches: [main]
    paths-ignore: [.github/**]
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "event that triggered the workflow: ${{ github.event_name }}"
          echo "branch name: ${{ github.ref }} and your repo is ."
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
