name: Hello World Docker CI
on: 
  push:
    branches: [main]
    paths: [hello-world-docker-action/**]
  workflow_dispatch:
    
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout:"
        uses: actions/checkout@v3.3.0

      - name: "Run my container action"
        id: hello-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: '@bambalooon'

      - name: "Output time from action"
        run: echo "time ${{ steps.hello-action.outputs.time }}"
          
